version: '2.3'
services:
  object_detection:
    build:
      context: object_detection/
    ports:
      - "8000:8000"
    runtime: nvidia
    volumes:
      - ./object_detection:/object_detection
    restart: on-failure